/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __EBOOK_STY_H__
#define __EBOOK_STY_H__

#define  UTIL_SCENE    0xe686173d
#define  PIC_HEADBAR    0xc64cc7b4
#define  STR_EBOOK    0xccf9dbce
#define  STR_SURE_DELETE    0xd31342c3
#define  STR_DELETING    0xef807704
#define  PIC_OPT_DOT    0x2be4326e
#define  STR_NOT_FOUND    0x48fed492
#define  STR_FILE_OPEN_FAIL    0x7519a924
#define  PIC_BACKGROUND    0x4da5a47f
#define  STR_NO_DISK    0xea3e44df
#define  MAINMENU_UPRIGHT_SCENE    0x3f51fc49
#define  STR_READING    0x12f5953c
#define  STR_DIRECTORY_LIST    0x1adea524
#define  STR_BOOKMARK_LIST    0xfd3b8f23
#define  DIRLIST_UPRIGHT_SCENE    0xd3fc7f42
#define  BOOKMARK_UPRIGHT_SCENE    0x163b4daf
#define  STR_NO_BOOKMARK    0xf294cf10
#define  READ_UPRIGHT_SCENE    0x13aaf2fb
#define  STR_TOO_LARGE    0x6e7bf956
#define  STR_BOOKMARK_FULL    0x3e1f20fc
#define  STR_ADD_BOOKMARK_FAIL    0x13474b5b
#define  READ_RESGROUP    0x11bfe924
#define  PIC_BOOK    0xc9805958
#define  PIC_BAR    0x48f2f10e
#define  REG_HAND_AUTO    0xea73d240
#define  STR_FILE_NAME    0xe9410c00
#define  STR_PAGE    0x10bdf799
#define  LAYOUT_RESGROUP    0x8d5899e6
#define  STR_FONT_LAYOUT1    0x5eed2e91
#define  STR_FONT_LAYOUT2    0x5eed2e92
#define  STR_FONT_LAYOUT3    0x5eed2e93
#define  ERASE_TEXT_RESGROUP    0x839b2c08
#define  FUSION_RECT_RESGROUP    0xe19fcaff
#define  OPTION_RESGROUP    0xbc7a5c4d
#define  STR_EB_SKIP    0x279cfa75
#define  STR_EB_AUTOT    0xb7bbe47b
#define  STR_SEC    0x22f3be17
#define  STR_EBK_MRK    0x2bb0d4b9
#define  STR_EB_SEL_CODE    0xa0bb9a74
#define  STR_EB_FONT    0x365b8da7
#define  STR_EB_L_FON    0x99eabce8
#define  STR_EB_M_FON    0xf168e2b9
#define  STR_EB_S_FON    0xaa26207f
#define  STR_EB_FONT_COLOR    0x8ca4f5cb
#define  STR_DEFAULT    0xbd2e09ff
#define  STR_COLOR1    0x3ff67416
#define  STR_COLOR2    0x3ff67415
#define  STR_COLOR3    0x3ff67414
#define  STR_COLOR4    0x3ff67413
#define  STR_MDELFILE    0x89f7eb4a
#define  STR_PAGE_EF    0xf6581ed
#define  STR_OFF    0x463919b7
#define  STR_MOVE_PAGE    0x4dd2ad9f
#define  STR_TURN_PAGE    0x96c235e9
#define  PIC_SIDELONG_BG    0x6381fd12
#define  READ_SIDELONG_SCENE    0xdbd36d65
#define  STR_INVALID_FORMAT    0xfbd910c5

#endif /* #ifndef __EBOOK_STY_H__ */
