/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __CALCULAT_STY_H__
#define __CALCULAT_STY_H__

#define  CALCULAT_UPRIGHT_SCENE    0xc0ffeebc
#define  PIC_BG    0xd34492b2
#define  PIC_KEY    0x590453f4
#define  PIC_BACKSPACE    0xed5c16d4
#define  PIC_CE    0xd2449127
#define  PIC_C    0x67da0e56
#define  STR_RESULT    0x6c836433
#define  PIC_DIV    0xece4e8a8
#define  PIC_SIGN    0xc776755c
#define  PIC_DAOSHU    0x76925495
#define  PIC_CENT    0x9d99c3e5
#define  PIC_MC    0xd44494cb
#define  PIC_MR    0xd44494da
#define  PIC_MSUB    0x3dc724be
#define  PIC_MADD    0x829a71b9
#define  PIC_MULTI    0xb427c4b6
#define  PIC_SUB    0x38c98a67
#define  PIC_ADD    0x53ec46ac
#define  PIC_EQUAL    0xedd01a25
#define  PIC_DOT    0xeee4ec70
#define  PIC_NUM0    0xdb3ddb13
#define  PIC_NUM1    0xdb3ddb12
#define  PIC_NUM2    0xdb3ddb11
#define  PIC_NUM3    0xdb3ddb10
#define  PIC_NUM4    0xdb3ddb17
#define  PIC_NUM5    0xdb3ddb16
#define  PIC_NUM6    0xdb3ddb15
#define  PIC_NUM7    0xdb3ddb14
#define  PIC_NUM8    0xdb3ddb1b
#define  PIC_NUM9    0xdb3ddb1a
#define  PIC_SQRT    0xa43a1385
#define  PIC_MEMORY    0x5347234a
#define  RESGRO_HEADBAR    0x3f870758
#define  PIC_ICON    0x49fdcac0
#define  STR_TITLE    0x21aea382
#define  STR_NODISK    0x9c62efca
#define  CALCULAT_SIDELONG_SCENE    0x54f7eab8

#endif /* #ifndef __CALCULAT_STY_H__ */
