/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __CALENDAR_STY_H__
#define __CALENDAR_STY_H__

#define  CALENDAR_UPRIGHT_SCENE    0xbd3f5a45
#define  PIC_BG    0xd34492b2
#define  PIC_BIGAREA    0xe83ddea0
#define  PIC_WEEK    0x80b31f
#define  PIC_AREA    0xcddb43fc
#define  STR_DATEINFO    0xa3ed6ca8
#define  PIC_LEFT    0xb8616a0
#define  PIC_RIGHT    0xc333c3d7
#define  PIC_LINE1    0x6b835b86
#define  PIC_LINE2    0x6b835b85
#define  PIC_SHIELD    0xa3dd6b60
#define  PICREG_NUM_Y    0xb8b6a307
#define  PICREG_NUM_W    0xb8b6a309
#define  PIC_ICON    0x49fdcac0
#define  STR_TITLE    0x21aea382
#define  PIC_POSITION1    0xdb6ff9cb
#define  PIC_POSITION2    0xdb6ff9c8
#define  PIC_POSITION3    0xdb6ff9c9
#define  PIC_POSITION4    0xdb6ff9ce
#define  PIC_POSITION5    0xdb6ff9cf
#define  PIC_POSITION6    0xdb6ff9cc
#define  PIC_POSITION7    0xdb6ff9cd
#define  PIC_POSITION8    0xdb6ff9c2
#define  PIC_BLOCK    0x31720246
#define  STR_SEL_COLOR    0x9d5434b8
#define  STR_NODISK    0x9c62efca
#define  CALENDAR_SIDELONG_SCENE    0xf006eadb

#endif /* #ifndef __CALENDAR_STY_H__ */
