/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __ANIM_OFF_STY_H__
#define __ANIM_OFF_STY_H__

#define  ANIMATION_POWEROFF_UPRIGHT_SCENE    0xffa7258c
#define  REG    0x69cb95ee
#define  ANIMATION_POWEROFF_SIDELONG_SCENE    0x2dd71c48

#endif /* #ifndef __ANIM_OFF_STY_H__ */
