/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __BROWSER_STY_H__
#define __BROWSER_STY_H__

#define  BROWSING_UPRIGHT_SCENE    0x532a8798
#define  PIC_BG    0xd34492b2
#define  PIC_TITLE    0x4c49b0e3
#define  STR_NOFILE    0xb0aaff7b
#define  STR_APP_NAME    0x9fb1cbbd
#define  STR_NO_SPACE    0x3b9ee62
#define  STR_LOW_POWER    0x5f6644c8
#define  STR_NO_MATCHING_ITEM    0x811dc685
#define  ENTRY_RESGROUP    0xc506c864
#define  STR_INT_MEM    0x6744479d
#define  STR_EXT_MEM    0xe62f9487
#define  STR_CAR_MEM    0xd0e712c0
#define  STR_NO_DISK    0xea3e44df
#define  ICONS_RESGROUP    0xd649f436
#define  PIC_FILE    0x5400ffc1
#define  PIC_FILE_SEL    0x32c2993c
#define  PIC_FILEH    0xfe929c9b
#define  PIC_FILEH_SEL    0x6cf15b86
#define  PIC_FOLD    0x380fddbe
#define  PIC_FOLD_SEL    0x99777dff
#define  PIC_FOLDH    0xfefa1252
#define  PIC_FOLDH_SEL    0x79ad275b
#define  PIC_MUSIC    0x8f3d514c
#define  PIC_MUSIC_SEL    0x77535a05
#define  PIC_PHOTO    0x5ebe9da1
#define  PIC_PHOTO_SEL    0xb5b4351c
#define  PIC_TXT    0xfdbc6105
#define  PIC_TXT_SEL    0xb0703d48
#define  PIC_VIDEO    0x586132b4
#define  PIC_VIDEO_SEL    0xe62359cd
#define  PIC_MUSICH    0xc986faec
#define  PIC_MUSICH_SEL    0x9d38c925
#define  PIC_PHOTOH    0xc712243b
#define  PIC_PHOTOH_SEL    0x7d2c82a6
#define  PIC_TXTH    0x748cba97
#define  PIC_TXTH_SEL    0x5b3183fa
#define  PIC_VIDEOH    0xd502d114
#define  PIC_VIDEOH_SEL    0x2b587dad
#define  OPTION_RESGROUP    0xbc7a5c4d
#define  STR_SEARCH_FILE    0x3c6e6115
#define  STR_SELECT_ALL    0x80e0c04c
#define  STR_MOVE    0x271d6acf
#define  STR_MOVE_CONFIRM    0xa7216282
#define  STR_MOVING    0x95775052
#define  STR_MOVE_SUCCEED    0xa181e6be
#define  STR_MOVE_FAILED    0x1046add
#define  STR_COPY    0x12d3425f
#define  STR_COPY_CONFIRM    0x9779bd12
#define  STR_COPING    0x5add63ae
#define  STR_COPY_SUCCEED    0x3c12f3ae
#define  STR_COPY_FAILED    0xe6f4c32d
#define  STR_DELETE    0x7e325e09
#define  STR_DELETE_CONFIRM    0x90d798ec
#define  STR_DELETING    0xef807704
#define  STR_DELETE_SUCCEED    0xea1eb9d0
#define  STR_DELETE_FAILED    0x4f7e8eab
#define  STR_REPLACE_CONFIRM    0x1d907385
#define  STR_SUBDIR_ERR    0x535d8e97
#define  STR_FILE_OPENING    0x412808ab
#define  STR_FILE_NOTSUP    0x3de39e8
#define  BROWSING_SIDELONG_SCENE    0x7b6fcf44
#define  STR_LOWPOWER    0x6686a061

#endif /* #ifndef __BROWSER_STY_H__ */
