/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __TVIN_STY_H__
#define __TVIN_STY_H__

#define  TVIN_RECORD_SCENE    0x83e16ee8
#define  STR_OPTION_RES    0xa4e62dc
#define  STR_SINGLE_REC1    0x1885823c
#define  STR_SINGLE_REC2    0x1885823f
#define  STR_SINGLE_REC3    0x1885823e
#define  STR_REPEAT_REC1    0x9cce4fef
#define  STR_REPEAT_REC2    0x9cce4fec
#define  STR_REPEAT_REC3    0x9cce4fed
#define  STR_SAVE_PATH    0x25d20ecf
#define  STR_SET_LCD    0xc30e9af4
#define  STR_START_DATE    0xae369f27
#define  STR_START_TIME    0xb6f2b7e0
#define  STR_RECORD_LENGTH    0xbfef355e
#define  STR_TV_ON    0xb311886a
#define  STR_TV_OFF    0x4699b200
#define  STR_REPEAT_WEEK    0x8e0dad04
#define  STR_SUNDAY    0xdb9daca4
#define  STR_MONDAY    0xb1c8fb70
#define  STR_TUESDAY    0x4b8fe1ad
#define  STR_WEDNESDAY    0x2fd53024
#define  STR_THURSDAY    0x5bf838e6
#define  STR_FRIDAY    0x75e201d
#define  STR_SATURDAY    0x3d5269c5
#define  STR_INTER_MEM    0x9c920564
#define  STR_CARD_MEMORY    0xc85fa074
#define  STR_EX_MEMORY    0x3311e8a3
#define  STR_SET_TIME    0x7cd1484
#define  STR_SET_DATE    0x2f38573b
#define  STR_SAVE_RECORD_FILE    0xacc4f5a6
#define  STR_RECORD_QUALITY    0xc2016af9
#define  STR_RECORD_QUALITY_LOW    0x1551ccea
#define  STR_RECORD_QUALITY_MEDIUM    0x97e6dc11
#define  STR_RECORD_QUALITY_HIGH    0x3becbaa0
#define  STR_RECORD_QUALITY_AUTO    0xf222dff9
#define  STR_TV_LOW_POWER    0xe1d721f
#define  PIC_TVIN_BUTTON    0xda908317
#define  PIC_TVIN_PROGRESS_HL    0xafed5f69
#define  PIC_TVIN_PROGRESS_DEHL    0x2900d8b0
#define  PICREGION_BUTTON_ICON    0x867c7011
#define  STR_RECORD_TIME    0xb541e80d
#define  PIC_TVIN_PROGRESS    0x44c2606e
#define  PIC_TVIN_OPTION_DOT    0xed316668
#define  STR_RECORD_REMAIN    0x5e00ee56
#define  STR_HB_TITLE    0xd9435a91
#define  PIC_TVIN_ICON    0xd52ce5c4
#define  PBAR_POSITION_RES    0xe1e38bfc
#define  STR_DISK_FULL    0x35836885
#define  STR_DISKINS    0xe6d59575
#define  STR_NODISK    0x9c62efca
#define  TVIN_PALNTSC_SIDELONG_SCENE    0xb4bc3fd2
#define  PIC_PALNTSC_BG    0x11cef694
#define  STR_PALNTSC_RES    0x4a3fff68
#define  STR_TV_PAL    0x51ab0cf4
#define  STR_TV_NTSC    0xadad3ffd
#define  PIC_TVIN_LIST_DOT    0xf72bc2af
#define  STR_CABLE_INSERT_INFO    0x46fefe00
#define  STR_TVOUT_INFO    0xe7f7841
#define  STR_DEV_FAILED    0x2125dcbf
#define  TVIN_PALNTSC_UPRIGHT_SCENE    0xe9f4e93a
#define  STR_LOW_POWER    0x5f6644c8

#endif /* #ifndef __TVIN_STY_H__ */
