/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __RECORDER_STY_H__
#define __RECORDER_STY_H__

#define  RECORDING_UPRIGHT_SCENE    0xbf622f86
#define  PIC_BG    0xd34492b2
#define  PIC_WORD_STATUS    0x4d9d6d28
#define  STR_FILENAME    0x1c32f7e7
#define  PIC_PBBG    0x5f73aaf8
#define  PIC_PB    0xc14476dd
#define  STR_CURTIME    0x31dbbaa1
#define  STR_TOTALTIME    0xcc06df49
#define  PIC_COLOR_STATUS    0x40acc465
#define  PIC_TAPE    0x7a9e0d37
#define  PIC_VOL_BG    0x452834f0
#define  PIC_VOL5    0x486774ff
#define  PIC_VOL4    0x486774fe
#define  PIC_VOL3    0x486774f9
#define  PIC_VOL2    0x486774f8
#define  PIC_VOL1    0x486774fb
#define  OPTION_RESGROUP    0xbc7a5c4d
#define  STR_FORMAT    0xe2779681
#define  STR_QUALITY    0x1c0ee47b
#define  STR_GAIN    0xe4b11061
#define  STR_MODE    0x351d80d1
#define  STR_SAVEPATH    0x605d739a
#define  OPTION_FORMAT_RESGROUP    0x467e2b05
#define  STR_WAV    0x36fcd87a
#define  STR_MP3    0xc344146
#define  STR_WMA    0x3afcde39
#define  OPTION_QUALITY_RESGROUP    0xdc3d055b
#define  STR_LOW    0x5d30ef36
#define  STR_MEDIUM    0x7afd9255
#define  STR_HIGH    0x4788f1d4
#define  OPTION_MODE_RESGROUP    0x4bccaacd
#define  STR_MIC    0x3343309
#define  STR_LINEIN    0x96181157
#define  OPTION_SAVEPATH_RESGROUP    0x2d032b90
#define  STR_INTERNAL    0x7fe9458b
#define  STR_CARD    0xe0d9033a
#define  STR_EXTERNAL    0xd3f6186d
#define  WIDGET_HEADBAR_RESGROUP    0xf68fdbd0
#define  PIC_HBAR    0xc4d81008
#define  STR_HBAR    0x1d9e759f
#define  WIDGET_DIALOG_RESGROUP    0x5cb13e99
#define  STR_DIALOG_STOPREC    0x270c1d6b
#define  STR_DIALOG_DISKINFO    0x3b4d8650
#define  STR_DIALOG_SAVEFILE    0x937ccc62
#define  STR_DIALOG_LOWBAT    0x4f62f3f4
#define  STR_DIALOG_NODISK    0xde5ebafd
#define  STR_DIALOG_DISKINS    0xa57470d0
#define  WIDGET_ADJUST_RESGROUP    0x4ca25482
#define  STR_ADJUST    0xf4625da5
#define  PIC_SELECT    0x16fc7b2f
#define  RECORDING_SIDELONG_SCENE    0x30a2c72e

#endif /* #ifndef __RECORDER_STY_H__ */
