/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __ANIM_ON_STY_H__
#define __ANIM_ON_STY_H__

#define  ANIMATION_POWERON_UPRIGHT_SCENE    0xee295ec8
#define  REG    0x69cb95ee
#define  ANIMATION_POWERON_SIDELONG_SCENE    0x906ca0b4

#endif /* #ifndef __ANIM_ON_STY_H__ */
