/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __WATCH_STY_H__
#define __WATCH_STY_H__

#define  STOPWATCH_UPRIGHT_SCENE    0x91b2a10e
#define  PIC_BG    0xd34492b2
#define  PIC_AREA    0xcddb43fc
#define  PIC_DOT2    0x82603462
#define  PIC_DOT2_2    0x1a2fe969
#define  PIC_DOT1    0x82603461
#define  PIC_COVER    0x5e324930
#define  PICREGION1    0x17063c8d
#define  PICREGION2    0x17063c8e
#define  PICREGION3    0x17063c8f
#define  PICREGION4    0x17063c88
#define  PICREGION5    0x17063c89
#define  PICREGION6    0x17063c8a
#define  PICREGION_SHOW_NUM    0x99fc9529
#define  STRING1    0x1566eb38
#define  STRING2    0x1566eb3b
#define  STRING3    0x1566eb3a
#define  STRING4    0x1566eb3d
#define  STRING5    0x1566eb3c
#define  STRING6    0x1566eb3f
#define  STR_IDX1    0xaf8a28de
#define  STR_IDX2    0xaf8a28dd
#define  STR_IDX3    0xaf8a28dc
#define  STR_IDX4    0xaf8a28db
#define  STR_IDX5    0xaf8a28da
#define  STR_IDX6    0xaf8a28d9
#define  RESGROUP_HEADBAR    0x5eb4eeeb
#define  PIC_ICON    0x49fdcac0
#define  STR_TITLE    0x21aea382
#define  STR_RESTART    0xa99864b9
#define  PIC_POSITION1    0xdb6ff9cb
#define  PIC_POSITION2    0xdb6ff9c8
#define  PIC_POSITION3    0xdb6ff9c9
#define  PIC_POSITION4    0xdb6ff9ce
#define  PIC_POSITION5    0xdb6ff9cf
#define  PIC_POSITION6    0xdb6ff9cc
#define  PIC_POSITION7    0xdb6ff9cd
#define  STR_NODISK    0x9c62efca
#define  STOPWATCH_SIDELONG_SCENE    0x21c0fa46

#endif /* #ifndef __WATCH_STY_H__ */
