/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __USB_STY_H__
#define __USB_STY_H__

#define  UTIL_SCENE    0xe686173d
#define  PIC_BACKGROUND    0x4da5a47f
#define  PIC_SIDELONG_BG    0x6381fd12
#define  UDISK_UPRIGHT_SCENE    0xe95a61cd
#define  REG_STATUS_FRAME    0x6af96131
#define  STR_UPGRADE    0x24f1d2d4
#define  STR_DONOT_DISCONNECT    0xd5e6023
#define  UDISK_SIDELONG_SCENE    0xd64b4a53
#define  MTP_UPRIGHT_SCENE    0x72c82716
#define  MTP_SIDELONG_SCENE    0x2841e17e
#define  CHARGE_UPRIGHT_SCENE    0x7a799c33
#define  REG_BATTERY    0x359419cc
#define  STR_NO_BATTERY    0x30941a8f
#define  STR_BATTERY_CUT    0xa38418ca
#define  STR_CHARGE_FULL    0xda0dff80
#define  CHARGE_SIDELONG_SCENE    0xf9672f6d
#define  UPGRADE_UPRIGHT_SCENE    0x25ab4f13
#define  PIC_BAR    0x48f2f10e
#define  PIC_BAR_HL    0xf06d4c9
#define  REG_WAIT    0x380e0732
#define  UPGRADE_SIDELONG_SCENE    0x16e9c80d
#define  UPGRADE_SCENE    0x3ca1eead
#define  SCENE_MAINMENU    0x2c81dda5

#endif /* #ifndef __USB_STY_H__ */
