/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __LAUNCHER_STY_H__
#define __LAUNCHER_STY_H__

#define  DESKTOP_UPRIGHT_SCENE    0xf83fc037
#define  STR_APP_NAME    0x9fb1cbbd
#define  STR_APP_NAME_P1    0x432310b9
#define  STR_APP_NAME_P2    0x432310ba
#define  STR_APP_NAME_P3    0x432310bb
#define  APP_ICON_RESGROUP    0xaacdc789
#define  PIC_DESKTOP_BG    0x54d51c85
#define  PIC_MUSIC_1    0x3a7d1910
#define  PIC_MUSIC_2    0x3a7d1913
#define  PIC_MUSIC_3    0x3a7d1912
#define  PIC_MUSIC_4    0x3a7d1915
#define  PIC_VIDEO_1    0x566f0788
#define  PIC_VIDEO_2    0x566f078b
#define  PIC_VIDEO_3    0x566f078a
#define  PIC_VIDEO_4    0x566f078d
#define  PIC_TVIN_1    0x9de77670
#define  PIC_TVIN_2    0x9de77673
#define  PIC_TVIN_3    0x9de77672
#define  PIC_TVIN_4    0x9de77675
#define  PIC_PHOTO_1    0x8d8ef175
#define  PIC_PHOTO_2    0x8d8ef176
#define  PIC_PHOTO_3    0x8d8ef177
#define  PIC_PHOTO_4    0x8d8ef170
#define  PIC_CAMERA_1    0x8c27a042
#define  PIC_CAMERA_2    0x8c27a041
#define  PIC_CAMERA_3    0x8c27a040
#define  PIC_CAMERA_4    0x8c27a047
#define  PIC_RECORDER_1    0x28aeff2d
#define  PIC_RECORDER_2    0x28aeff2e
#define  PIC_RECORDER_3    0x28aeff2f
#define  PIC_RECORDER_4    0x28aeff28
#define  PIC_RADIO_1    0xfb4ac790
#define  PIC_RADIO_2    0xfb4ac793
#define  PIC_RADIO_3    0xfb4ac792
#define  PIC_RADIO_4    0xfb4ac795
#define  PIC_EBOOK_1    0x4ae1d76f
#define  PIC_EBOOK_2    0x4ae1d76c
#define  PIC_EBOOK_3    0x4ae1d76d
#define  PIC_EBOOK_4    0x4ae1d76a
#define  PIC_GAMES_1    0x9faf8498
#define  PIC_GAMES_2    0x9faf849b
#define  PIC_GAMES_3    0x9faf849a
#define  PIC_GAMES_4    0x9faf849d
#define  PIC_TOOLS_1    0x5a18fbb8
#define  PIC_TOOLS_2    0x5a18fbbb
#define  PIC_TOOLS_3    0x5a18fbba
#define  PIC_TOOLS_4    0x5a18fbbd
#define  PIC_BROWSER_1    0xd7baaf1
#define  PIC_BROWSER_2    0xd7baaf2
#define  PIC_BROWSER_3    0xd7baaf3
#define  PIC_BROWSER_4    0xd7baaf4
#define  PIC_SETTING_1    0x9f28e3bd
#define  PIC_SETTING_2    0x9f28e3be
#define  PIC_SETTING_3    0x9f28e3bf
#define  PIC_SETTING_4    0x9f28e3b8
#define  PIC_HBAR_TOOL    0xff8f0fd
#define  PIC_HBAR_GAME    0xad9e93fd
#define  DESKTOP_SIDELONG_SCENE    0xe9dc8b71

#endif /* #ifndef __LAUNCHER_STY_H__ */
