/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __EMULATOR_STY_H__
#define __EMULATOR_STY_H__

#define  EMULATOR_UPRIGHT_SCENE    0x3539faea
#define  PIC_BG    0xd34492b2
#define  PIC_ICON    0x49fdcac0
#define  STR_DISP    0x56b10284
#define  STR_TITLE    0x21aea382
#define  STR_SAVE    0x17ab3bbf
#define  STR_RESTART    0xa99864b9
#define  STR_LOAD    0xd4086f24
#define  STR_SETTING    0x423202f4
#define  STR_QUIT    0x43820655
#define  STR_SOUND    0xdd82c305
#define  STR_KEY    0x332e6ef5
#define  STR_NO_FILE    0xc5f61be2
#define  STR_FULL_SCREEN    0xca0cd6a6
#define  STR_HAS_SAVED    0x53a8673c
#define  STR_SURE_MODIFY    0x1b6d8cdc
#define  STR_FAIL_OPEN    0x1132efcf
#define  STR_NOSUPP    0xcbb16669
#define  STR_NODISK    0x9c62efca
#define  STR_SAVE_ERR    0x7e6efa53
#define  EMULATOR_SIDELONG_SCENE    0x48aa0402

#endif /* #ifndef __EMULATOR_STY_H__ */
