/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __PL_GENER_STY_H__
#define __PL_GENER_STY_H__

#define  PLIST_GENERATE_UPRIGHT_SCENE    0xf0451519
#define  PIC_BG    0xd34492b2
#define  REG_WAIT    0x380e0732
#define  PIC_PBAR_BG    0x813389a
#define  PIC_PBAR_HL    0xfe132953
#define  RESGROUP_PBAR_HIGHLIGHT_RECT    0xc6ec1ded
#define  STR_WAIT    0xf508a6ab
#define  STR_NOSPACE    0x625fbb59
#define  PLIST_GENERATE_SIDELONG_SCENE    0xf3b1ac5f
#define  PLIST_GENERATE_SCENE    0xa5f6a137

#endif /* #ifndef __PL_GENER_STY_H__ */
